### ISSUE TITLE
0.19 Upgrade

### ISSUE THREAD

**Issue by lukewestby** [rluiten/elm-text-search#12]
Hey @rluiten! Are you planning to continue maintaining this and related packages into Elm 0.19? A response either way will help us at NoRedInk to plan our codebase upgrade. Thank you!

**Comment by rluiten** [comment]
Yes, I started looking at the 0.19 upgrade doc last night.
I currently plan to start on weekend.
Most packages should be easy, the date one not so simple I think.

**Comment by Hywan** [comment]
It would be very lovely to support 0.19 :-). Thanks for your excellent work!

**Comment by Hywan** [comment]
May we help you?

**Comment by rluiten** [comment]
I am up to updating the examples and some of the code examples in the documentation.
The core package and its tests seem to be fine in 0.19 as yesterday, though not yet published due to documentation changes required.
The other packages I wrote that it depends on have been updated and published recently.

**Comment by rluiten** [comment]
I had done the updating of one of the examples last night.
I just finished the other 3 and there was only one example in the inline comments that needed to be updated.
I thought I remembered more oh well done now.

elm-text-search 5.0.0  has been published.

**Comment by Hywan** [comment]
\o/ 🎉  Thanks!
