### ISSUE TITLE
Is there a way to make the tokenizer ignore apostrophes? 

### ISSUE THREAD

**Issue by eniac314** [rluiten/elm-text-search#16]
I am using the library to index a corpus of recipes in French. I replaced the default stop word list by a French one, so far so good.

In French we often use `l'` or `d'` as determiner before nouns as in `de l'eau`, `l'ail` meaning some water and the garlic. I think the tokenizer includes `l'` or `d'` with the following words, so a search for `ail` or `eau` does not work, probably because the search string tokens are expanded to the right. The fact that searching for `john` in a text containing `John's book` works seems to confirm that.  

Ideally the index would only register `ail` and `eau` as tokens and ignore what comes before, as it it not relevant in the context of a search. 

Is there a way to change the index config in order to achieve this effect?

**Comment by rluiten** [comment]
It's been quite a while since I have touched this project or the related https://github.com/rluiten/stemmer project so I might be forgetting things.

If you look at `getDefaultIndexConfig` in Defaults.elm.
It identifies the default values for an Index Config.
* initialTransformFactories
* transformFactories
* filterFactories

As you mention having your own French stop word list you must already be setting `filterFactories` which is a good start.

I think you will find this issue in this repository worth reading in relation to how indexing and stemmers work.
* wildcards https://github.com/rluiten/elm-text-search/issues/6

    * This comment from that thread will likely help you, as it makes it clear how to get rid of the english stemmer.

        > Just to circle back around, by passing an empty list for the transformFactories
        > (bypassing the stemmer), we got the behavior we wanted
        > (all prefixes of "banned" match "banned"). It does increase the size of the index,
        > but in our case, it's a small index and the increase is small, so it's worth it.

I suspect that a French stemmer may remove the `l'` as one of its steps in stemming.

To get good behavior in French I suspect you will need to implement your own French language stemmer and use it. A quick search uncovered this https://yomguithereal.github.io/talisman/stemmers/french as a possible source for how to go about creating a stemmer for French.

You may also want to look at the English stemmer I linked above as a starting point or template to create a stemmer.

I think once you get an understanding of how a French stemmer works it may resolve a big part of your desired behavior.

**Comment by eniac314** [comment]
Thank you for your detailed answer. I made a naive port of the French version of the porter stemming algorithm from the page you linked. 
I also made a small function removing the apostrophes and  the grammatical words coming before them. 
I'll try putting everything together after a bit of tidying up!

**Comment by rluiten** [comment]
I am interested to hear how you go.

If the result seems to behave well  it might worth adding an example to this repository
of the use of your French stop word list and stemmer.

This would require that your stemmer and stop word list be published as elm packages.

**Comment by eniac314** [comment]
Everything seems to be working all right for now, I have not tried to optimize it for speed yet, but the stemmer passes all the tests at  http://snowball.tartarus.org/algorithms/french/voc.txt .

When building the index I replaced the original stemmer like this:
```
ElmTextSearch.newWith
    { indexType = "ElmTextSearch - Customized French Stop Words"
    , ref = Date.toIsoString << .date
    , fields =
        []
    , listFields = [ ( Dict.keys << .recipes, 5.0 ), ( Dict.values << .recipes, 1.0 ) ]
    , initialTransformFactories = Index.Defaults.defaultInitialTransformFactories
    , transformFactories = [ (\func index -> ( index, func )) (FrenchStemmer.stemmer True) ]
    , filterFactories = [ createFilterFunc frenchStopWords ]
    }
```  

The `Bool` parameter is enabling the trimming of the prefixes ending with apostrophes. `(\func index -> ( index, func ))` is replacing `Index.Utils.createFuncCreator` as it is not exposed by your library I think.

**Comment by eniac314** [comment]
So here is the published package: https://package.elm-lang.org/packages/eniac314/french-stemmer/latest/
I modelled the tests and documentation after yours. 
I also took the liberty to reuse your `buildStemmerFixtureElm2.js` script. Please tell me if this is not ok or if I should credit you for it in the readme. 
Thanks again for your help.

**Comment by rluiten** [comment]
That looks really good.
Sounds like its useful, and now can help other's if they need it.
I have no problem with anyone grabbing code for whatever reason.

I'd be happy to receive a pull request to this Repository with a simple example / demo of using your French Stemmer if you fell up to it?
