### ISSUE TITLE
No hits for partial words

### ISSUE THREAD

**Issue by joakimk** [rluiten/elm-text-search#2]
If you run the example in the readme it finds a result, but if you then remove the last two characters from "explanations" so you have "explanatio" then it won't find anything. This is different from lunr.js behavior.

The API docs seems to suggest that this should not happen:
`Each token is expanded, so that the term "he" might be expanded to "hello" and "help" if those terms were already included in the document index.`

http://package.elm-lang.org/packages/rluiten/elm-text-search/2.0.0/ElmTextSearch#search

Is this a bug or am I misunderstanding the docs? :)

**Comment by rluiten** [comment]
Yes you are reading the document correctly it should find prefix words by expanding words and searching for those expanded words. However in this case the word is not a prefix due to how word stemming is used in the index.

For this example it is the expected result to return nothing for that search time. I do believe lunr.js will also return nothing for this example case. Have you actually test run this example in lunr.js and see it return a result or are you depending on the documentation saying it expands words that should mean it would work ?

You have uncovered a case that behaves this way due to the word stemming algorithm used in indexing documents.

When a document is added to the index every word is run through a word stemmer. In this case the default stemmer is the porter stemmer which is an english language word stemmer.

For this example the result of indexing the document produces the following list of words as being in the example document extracted from the fields title and body.

["document","exampl","explan","first","titl","word"]

The point of the word stemmer is to reduce the variations in equivalent words down to a common stem words. In this case "atoin" and "ations" are a common suffix on english words that don't change the meaning of the word in this case the stem word of "explanations" is "explan".

Also the search terms you enter are also stemmed before they are searched for in the index. By modifying the search term to "explanatio" you are causing the word stemmer to not recognise the word and it does not get stemmed so you are seaching for "explanatio" and not "explan" or any shorter form of the word like "expl" or something.

This is an expected behaviour of an indexer that uses word stemming. The combination of word stemming and a list of common words to not index (a stop word filter) the number of words in the document that need to be held for indexing is significantly reduced and makes the resource requirements of index creation, storage and search lower.

Hope that explanation makes sense, to change the behaviour of this would require the word stemmer to behave quite differently.

**Comment by joakimk** [comment]
Tried to reproduce it. It seems "explainatio" won't work in lunr.js either, but "ex" does.

https://jsfiddle.net/ow7mb00h/

The behavior I like about lunr.js which I don't see in elm-text-search is that it returns results from the first character, a search for "e" returns results, and as the user types the results get better.

**Comment by rluiten** [comment]
Ok that is a problem it should be returning stuff for proper prefixes. 
I will dig into this further.

**Comment by rluiten** [comment]
I have published a 2.0.1 to fix this problem.
Thank you for the report, I also added a few test cases which I had had not covered before.

**Comment by rluiten** [comment]
Oh please let me know if it does not solve related issues.

**Comment by joakimk** [comment]
Thank you. It works as I expect now. I'll get back to you if I find anything else.
